"""Stage 6: automatic overview screenplay generation.

On preprocessing completion the tool gifts the user a free "overview" screenplay
(Design.md §7.4.7). The overview is a single compact document; we persist it as
an ``overview`` Screenplay plus one Episode whose ``content`` holds the whole
document, so it is retrievable and exportable through the existing endpoints
with no schema migration.

When the LLM is configured the document is generated by the generation agent
using the overview schema; otherwise a deterministic template is assembled from
the preprocessing artefacts (the design's ``fallback_basic_overview``).
"""

import json
import re

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import (
    Chapter,
    Episode,
    EpisodeStatus,
    Novel,
    QualityLevel,
    SchemaType,
    Screenplay,
    ScreenplayStatus,
)
from app.services.generation_service import generation_service
from app.services.llm_service import LLMError, llm_service

_CHAPTER_REF = re.compile(r"第\s*(\d+)\s*章")


class OverviewService:
    async def generate_overview(
        self, db: AsyncSession, novel: Novel
    ) -> tuple[Screenplay, Episode]:
        chapters = list(
            (
                await db.execute(
                    select(Chapter)
                    .where(Chapter.novel_id == novel.id)
                    .order_by(Chapter.chapter_num.asc())
                )
            ).scalars()
        )

        document: dict | None = None
        quality = QualityLevel.good
        if llm_service.enabled:
            try:
                document = await self._generate_with_llm(novel, chapters)
            except LLMError:
                document = None
        if not self._is_usable_document(document):
            document = self._fallback_document(novel, chapters)
            quality = QualityLevel.fallback

        adaptation_plan = self._adaptation_plan_from_document(document, chapters)
        screenplay = (
            await db.execute(
                select(Screenplay).where(
                    Screenplay.novel_id == novel.id,
                    Screenplay.schema_type == SchemaType.overview,
                    Screenplay.is_auto_generated.is_(True),
                )
            )
        ).scalar_one_or_none()
        if screenplay:
            screenplay.schema_version = "overview-1.0"
            screenplay.status = ScreenplayStatus.completed
            screenplay.quality = quality
            screenplay.adaptation_plan = adaptation_plan
            screenplay.style_preferences = {"title": f"{novel.title} 概览版"}
        else:
            screenplay = Screenplay(
                novel_id=novel.id,
                schema_type=SchemaType.overview,
                schema_version="overview-1.0",
                status=ScreenplayStatus.completed,
                is_auto_generated=True,
                quality=quality,
                # Mirror the document's episode breakdown into ``adaptation_plan`` so
                # the overview screenplay is renderable through the same plan-based UI
                # path as ordinary screenplays (the full document still lives on the
                # episode below).
                adaptation_plan=adaptation_plan,
                style_preferences={"title": f"{novel.title} 概览版"},
            )
            db.add(screenplay)
        await db.flush()

        episode = (
            await db.execute(
                select(Episode).where(
                    Episode.screenplay_id == screenplay.id,
                    Episode.episode_num == 1,
                )
            )
        ).scalar_one_or_none()
        if episode:
            episode.title = novel.title
            episode.source_chapters = [ch.chapter_num for ch in chapters]
            episode.status = EpisodeStatus.done
            episode.content = document
            episode.error_message = None
        else:
            episode = Episode(
                screenplay_id=screenplay.id,
                episode_num=1,
                title=novel.title,
                source_chapters=[ch.chapter_num for ch in chapters],
                status=EpisodeStatus.done,
                content=document,
            )
            db.add(episode)
        await db.flush()
        return screenplay, episode

    def _adaptation_plan_from_document(
        self, document: dict, chapters: list[Chapter]
    ) -> dict:
        """Project the overview document's episode list into the ``adaptation_plan``
        shape the frontend reads (``episode_num`` / ``source_chapters`` /
        ``one_line_summary``). The overview schema uses ``episode_number`` and a
        single ``source_chapter`` (often a chapter *title*), so we normalise both
        here and resolve chapter references to integer chapter numbers — never
        titles — so the plan can drive episode creation downstream."""
        title_to_num = {ch.title: ch.chapter_num for ch in chapters}
        doc_episodes = document.get("episodes") or []
        episodes = []
        for index, ep in enumerate(doc_episodes, start=1):
            if not isinstance(ep, dict):
                continue
            raw = ep.get("source_chapters")
            candidates = raw if isinstance(raw, list) else [raw if raw is not None else ep.get("source_chapter")]
            source_chapters: list[int] = []
            for candidate in candidates:
                if isinstance(candidate, bool):
                    continue
                if isinstance(candidate, int):
                    source_chapters.append(candidate)
                elif isinstance(candidate, str):
                    # Free-text refs like "第1章 标题, 第3章 标题" -> [1, 3];
                    # otherwise a pure-digit string, otherwise an exact title.
                    matches = _CHAPTER_REF.findall(candidate)
                    if matches:
                        source_chapters.extend(int(m) for m in matches)
                    elif candidate.strip().isdigit():
                        source_chapters.append(int(candidate.strip()))
                    elif candidate in title_to_num:
                        source_chapters.append(title_to_num[candidate])
            # dedupe, preserve order
            seen: set[int] = set()
            source_chapters = [n for n in source_chapters if not (n in seen or seen.add(n))]
            episodes.append(
                {
                    "episode_num": ep.get("episode_number") or ep.get("episode_num") or index,
                    "title": ep.get("title") or f"第 {index} 集",
                    "source_chapters": source_chapters,
                    "one_line_summary": ep.get("one_line_summary") or ep.get("summary") or "",
                }
            )
        return {
            "episode_count": len(episodes) if episodes else document.get("estimated_episodes") or 0,
            "chapters_per_episode": max(len(chapters) // max(len(episodes), 1), 1),
            "total_chapters": len(chapters),
            "episodes": episodes,
        }

    async def _generate_with_llm(self, novel: Novel, chapters: list[Chapter]) -> dict:
        schema_definition = generation_service._schema_definition("overview")
        system_prompt = "\n".join(
            [
                "你是影视制片策划和小说改编评估专家。",
                "你的任务是基于小说预处理结果，生成供制片人/版权方快速判断项目价值的“概览版剧本”。",
                "必须只输出一个 JSON object，不要 Markdown，不要解释，不要 YAML。",
                "JSON 顶层必须包含这些字段：",
                "schema_version, schema_type, title, logline, hook, genre, estimated_episodes,",
                "target_audience, market_comparable, adaptation_difficulty, main_characters, plot_arc, episodes。",
                "market_comparable 必须给出可理解的市场类比，格式类似：节奏类似《X》，题材接近《Y》。",
                "adaptation_difficulty 必须是“低/中/高 —— 理由”的中文短句。",
                "episodes 必须是非空数组，每项包含 episode_number, title, source_chapter, one_line_summary, key_scenes。",
                "key_scenes 每项包含 location, characters, conflict, outcome, weight。",
                "不要编造原著没有的重大情节；可以基于摘要做影视化归纳和项目评估。",
            ]
        )
        user_payload = {
            "schema_definition": schema_definition,
            "novel": {
                "title": novel.title,
                "summary": novel.summary or "",
                "genres": novel.user_selected_genres or [],
                "character_arcs": novel.character_arcs or [],
                "foreshadowing": novel.foreshadowing or [],
            },
            "chapters": [
                {
                    "chapter_num": ch.chapter_num,
                    "title": ch.title,
                    "summary": ch.summary or "",
                    "key_events": ch.key_events or [],
                }
                for ch in chapters
            ],
        }
        last_document: dict | None = None
        for attempt in range(2):
            document = await llm_service.generate_structured(
                system=system_prompt,
                user=json.dumps(user_payload, ensure_ascii=False),
                temperature=0.2,
            )
            document = self._normalise_llm_document(document, novel)
            last_document = document
            if self._is_ai_complete_document(document):
                return document
            user_payload["retry_instruction"] = (
                "上一次输出缺少概览版关键字段。请重新输出完整 JSON，尤其必须补齐 "
                "market_comparable、adaptation_difficulty 和非空 episodes。"
            )
            user_payload["previous_invalid_output"] = document
        raise LLMError(f"Overview LLM output missing required fields: {last_document}")

    @staticmethod
    def _normalise_llm_document(document: dict, novel: Novel) -> dict:
        if isinstance(document.get("data"), dict):
            document = dict(document["data"])
        document["schema_version"] = "overview-1.0"
        document["schema_type"] = "overview"
        document.setdefault("title", novel.title)
        if not document.get("genre"):
            document["genre"] = (novel.user_selected_genres or [""])[0]
        return document

    @staticmethod
    def _is_ai_complete_document(document: dict | None) -> bool:
        if not isinstance(document, dict):
            return False
        required_text = ("logline", "market_comparable", "adaptation_difficulty")
        if any(not isinstance(document.get(key), str) or not document[key].strip() for key in required_text):
            return False
        episodes = document.get("episodes")
        if not isinstance(episodes, list) or not episodes:
            return False
        return any(
            isinstance(ep, dict)
            and str(ep.get("title") or "").strip()
            and str(ep.get("one_line_summary") or "").strip()
            for ep in episodes
        )

    @staticmethod
    def _is_usable_document(document: dict | None) -> bool:
        """Reject malformed LLM JSON before it reaches the UI.

        Some providers can return syntactically valid JSON that is semantically
        useless for the overview schema, for example ``{"data": -1.0}``. The
        frontend needs at least a logline or an episode list to render the
        overview page, so fall back when those fields are missing.
        """
        if not isinstance(document, dict):
            return False
        logline = document.get("logline")
        episodes = document.get("episodes")
        if isinstance(logline, str) and logline.strip():
            return True
        if isinstance(episodes, list) and any(isinstance(ep, dict) for ep in episodes):
            return True
        return False

    def _fallback_document(self, novel: Novel, chapters: list[Chapter]) -> dict:
        summary = novel.summary or ""
        arcs = novel.character_arcs or []
        return {
            "schema_version": "overview-1.0",
            "schema_type": "overview",
            "title": novel.title,
            "logline": summary[:100] if summary else "暂无",
            "hook": "",
            "genre": (novel.user_selected_genres or [None])[0],
            "estimated_episodes": max(len(chapters) // 2, 1),
            "market_comparable": "",
            "adaptation_difficulty": "待评估",
            "main_characters": [
                {
                    "name": arc.get("name", "未命名角色"),
                    "role": arc.get("role", ""),
                    "one_liner": self._arc_one_liner(arc),
                }
                for arc in arcs[:5]
            ],
            "plot_arc": {
                "setup": "",
                "inciting_incident": "",
                "rising_action": "",
                "climax": "",
                "resolution": "",
            },
            "episodes": [
                {
                    "episode_number": ch.chapter_num,
                    "title": ch.title,
                    "source_chapter": ch.title,
                    "one_line_summary": (ch.summary or "")[:100],
                    "key_scenes": [],
                }
                for ch in chapters[:10]
            ],
            "is_fallback": True,
        }

    @staticmethod
    def _arc_one_liner(arc: dict) -> str:
        if arc.get("one_liner"):
            return str(arc["one_liner"])
        inner = arc.get("arc")
        if isinstance(inner, dict):
            return str(inner.get("start", ""))[:50]
        if isinstance(inner, str):
            return inner[:50]
        return str(arc.get("arc_description", ""))[:50]


overview_service = OverviewService()
