"""Stage 6: automatic overview screenplay generation.

On preprocessing completion the tool gifts the user a free "overview" screenplay
(Design.md §7.4.7). The overview is a single compact document; we persist it as
an ``overview`` Screenplay plus one Episode whose ``content`` holds the whole
document, so it is retrievable and exportable through the existing endpoints
with no schema migration.

When the LLM is configured the document is generated by the generation agent
using the overview schema; otherwise a deterministic template is assembled from
the preprocessing artefacts (the design's ``fallback_basic_overview``).
"""

import json

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import (
    Chapter,
    Episode,
    EpisodeStatus,
    Novel,
    QualityLevel,
    SchemaType,
    Screenplay,
    ScreenplayStatus,
)
from app.services.generation_service import generation_service
from app.services.llm_service import LLMError, llm_service
from app.services.prompt_loader import prompt_loader


class OverviewService:
    async def generate_overview(
        self, db: AsyncSession, novel: Novel
    ) -> tuple[Screenplay, Episode]:
        chapters = list(
            (
                await db.execute(
                    select(Chapter)
                    .where(Chapter.novel_id == novel.id)
                    .order_by(Chapter.chapter_num.asc())
                )
            ).scalars()
        )

        document: dict | None = None
        quality = QualityLevel.good
        if llm_service.enabled:
            try:
                document = await self._generate_with_llm(novel, chapters)
            except LLMError:
                document = None
        if not document:
            document = self._fallback_document(novel, chapters)
            quality = QualityLevel.fallback

        screenplay = Screenplay(
            novel_id=novel.id,
            schema_type=SchemaType.overview,
            schema_version="overview-1.0",
            status=ScreenplayStatus.completed,
            is_auto_generated=True,
            quality=quality,
            adaptation_plan={},
            style_preferences={"title": f"{novel.title} 概览版"},
        )
        db.add(screenplay)
        await db.flush()

        episode = Episode(
            screenplay_id=screenplay.id,
            episode_num=1,
            title=novel.title,
            source_chapters=[ch.chapter_num for ch in chapters],
            status=EpisodeStatus.done,
            content=document,
        )
        db.add(episode)
        await db.flush()
        return screenplay, episode

    async def _generate_with_llm(self, novel: Novel, chapters: list[Chapter]) -> dict:
        system_prompt = prompt_loader.load("generation_agent")
        schema_definition = generation_service._schema_definition("overview")
        user_payload = {
            "task": "generate_overview",
            "schema_type": "overview",
            "schema_definition": schema_definition,
            "title": novel.title,
            "novel_summary": novel.summary or "",
            "character_arcs": novel.character_arcs or [],
            "chapters": [
                {"chapter_num": ch.chapter_num, "title": ch.title, "summary": ch.summary or ""}
                for ch in chapters
            ],
            "instruction": (
                "基于以上预处理素材生成概览版剧本 JSON，严格遵循 overview schema："
                "顶层含 schema_version、schema_type、title、logline、hook、genre、"
                "estimated_episodes、market_comparable、adaptation_difficulty、"
                "main_characters、plot_arc、episodes。不要编造原著没有的情节。"
            ),
        }
        document = await llm_service.generate_structured(
            system=system_prompt,
            user=json.dumps(user_payload, ensure_ascii=False),
        )
        document["schema_version"] = "overview-1.0"
        document["schema_type"] = "overview"
        document.setdefault("title", novel.title)
        return document

    def _fallback_document(self, novel: Novel, chapters: list[Chapter]) -> dict:
        summary = novel.summary or ""
        arcs = novel.character_arcs or []
        return {
            "schema_version": "overview-1.0",
            "schema_type": "overview",
            "title": novel.title,
            "logline": summary[:100] if summary else "暂无",
            "hook": "",
            "genre": (novel.user_selected_genres or [None])[0],
            "estimated_episodes": max(len(chapters) // 2, 1),
            "market_comparable": "",
            "adaptation_difficulty": "待评估",
            "main_characters": [
                {
                    "name": arc.get("name", "未命名角色"),
                    "role": arc.get("role", ""),
                    "one_liner": self._arc_one_liner(arc),
                }
                for arc in arcs[:5]
            ],
            "plot_arc": {
                "setup": "",
                "inciting_incident": "",
                "rising_action": "",
                "climax": "",
                "resolution": "",
            },
            "episodes": [
                {
                    "episode_number": ch.chapter_num,
                    "title": ch.title,
                    "source_chapter": ch.title,
                    "one_line_summary": (ch.summary or "")[:100],
                    "key_scenes": [],
                }
                for ch in chapters[:10]
            ],
            "is_fallback": True,
        }

    @staticmethod
    def _arc_one_liner(arc: dict) -> str:
        if arc.get("one_liner"):
            return str(arc["one_liner"])
        inner = arc.get("arc")
        if isinstance(inner, dict):
            return str(inner.get("start", ""))[:50]
        if isinstance(inner, str):
            return inner[:50]
        return str(arc.get("arc_description", ""))[:50]


overview_service = OverviewService()
