"""Stage 6: automatic overview screenplay generation.

On preprocessing completion the tool gifts the user a free "overview" screenplay
(Design.md §7.4.7). The overview is a single compact document; we persist it as
an ``overview`` Screenplay plus one Episode whose ``content`` holds the whole
document, so it is retrievable and exportable through the existing endpoints
with no schema migration.

When the LLM is configured the document is generated by the generation agent
using the overview schema; otherwise a deterministic template is assembled from
the preprocessing artefacts (the design's ``fallback_basic_overview``).
"""

import json
import re

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import (
    Chapter,
    Episode,
    EpisodeStatus,
    Novel,
    QualityLevel,
    SchemaType,
    Screenplay,
    ScreenplayStatus,
)
from app.services.generation_service import generation_service
from app.services.llm_service import LLMError, llm_service
from app.services.prompt_loader import prompt_loader

_CHAPTER_REF = re.compile(r"第\s*(\d+)\s*章")


class OverviewService:
    async def generate_overview(
        self, db: AsyncSession, novel: Novel
    ) -> tuple[Screenplay, Episode]:
        chapters = list(
            (
                await db.execute(
                    select(Chapter)
                    .where(Chapter.novel_id == novel.id)
                    .order_by(Chapter.chapter_num.asc())
                )
            ).scalars()
        )

        document: dict | None = None
        quality = QualityLevel.good
        if llm_service.enabled:
            try:
                document = await self._generate_with_llm(novel, chapters)
            except LLMError:
                document = None
        if not document:
            document = self._fallback_document(novel, chapters)
            quality = QualityLevel.fallback

        screenplay = Screenplay(
            novel_id=novel.id,
            schema_type=SchemaType.overview,
            schema_version="overview-1.0",
            status=ScreenplayStatus.completed,
            is_auto_generated=True,
            quality=quality,
            # Mirror the document's episode breakdown into ``adaptation_plan`` so
            # the overview screenplay is renderable through the same plan-based UI
            # path as ordinary screenplays (the full document still lives on the
            # episode below).
            adaptation_plan=self._adaptation_plan_from_document(document, chapters),
            style_preferences={"title": f"{novel.title} 概览版"},
        )
        db.add(screenplay)
        await db.flush()

        episode = Episode(
            screenplay_id=screenplay.id,
            episode_num=1,
            title=novel.title,
            source_chapters=[ch.chapter_num for ch in chapters],
            status=EpisodeStatus.done,
            content=document,
        )
        db.add(episode)
        await db.flush()
        return screenplay, episode

    def _adaptation_plan_from_document(
        self, document: dict, chapters: list[Chapter]
    ) -> dict:
        """Project the overview document's episode list into the ``adaptation_plan``
        shape the frontend reads (``episode_num`` / ``source_chapters`` /
        ``one_line_summary``). The overview schema uses ``episode_number`` and a
        single ``source_chapter`` (often a chapter *title*), so we normalise both
        here and resolve chapter references to integer chapter numbers — never
        titles — so the plan can drive episode creation downstream."""
        title_to_num = {ch.title: ch.chapter_num for ch in chapters}
        doc_episodes = document.get("episodes") or []
        episodes = []
        for index, ep in enumerate(doc_episodes, start=1):
            if not isinstance(ep, dict):
                continue
            raw = ep.get("source_chapters")
            candidates = raw if isinstance(raw, list) else [raw if raw is not None else ep.get("source_chapter")]
            source_chapters: list[int] = []
            for candidate in candidates:
                if isinstance(candidate, bool):
                    continue
                if isinstance(candidate, int):
                    source_chapters.append(candidate)
                elif isinstance(candidate, str):
                    # Free-text refs like "第1章 标题, 第3章 标题" -> [1, 3];
                    # otherwise a pure-digit string, otherwise an exact title.
                    matches = _CHAPTER_REF.findall(candidate)
                    if matches:
                        source_chapters.extend(int(m) for m in matches)
                    elif candidate.strip().isdigit():
                        source_chapters.append(int(candidate.strip()))
                    elif candidate in title_to_num:
                        source_chapters.append(title_to_num[candidate])
            # dedupe, preserve order
            seen: set[int] = set()
            source_chapters = [n for n in source_chapters if not (n in seen or seen.add(n))]
            episodes.append(
                {
                    "episode_num": ep.get("episode_number") or ep.get("episode_num") or index,
                    "title": ep.get("title") or f"第 {index} 集",
                    "source_chapters": source_chapters,
                    "one_line_summary": ep.get("one_line_summary") or ep.get("summary") or "",
                }
            )
        return {
            "episode_count": len(episodes) if episodes else document.get("estimated_episodes") or 0,
            "chapters_per_episode": max(len(chapters) // max(len(episodes), 1), 1),
            "total_chapters": len(chapters),
            "episodes": episodes,
        }

    async def _generate_with_llm(self, novel: Novel, chapters: list[Chapter]) -> dict:
        system_prompt = prompt_loader.load("generation_agent")
        schema_definition = generation_service._schema_definition("overview")
        user_payload = {
            "task": "generate_overview",
            "schema_type": "overview",
            "schema_definition": schema_definition,
            "title": novel.title,
            "novel_summary": novel.summary or "",
            "character_arcs": novel.character_arcs or [],
            "chapters": [
                {"chapter_num": ch.chapter_num, "title": ch.title, "summary": ch.summary or ""}
                for ch in chapters
            ],
            "instruction": (
                "基于以上预处理素材生成概览版剧本 JSON，严格遵循 overview schema："
                "顶层含 schema_version、schema_type、title、logline、hook、genre、"
                "estimated_episodes、market_comparable、adaptation_difficulty、"
                "main_characters、plot_arc、episodes。不要编造原著没有的情节。"
            ),
        }
        document = await llm_service.generate_structured(
            system=system_prompt,
            user=json.dumps(user_payload, ensure_ascii=False),
        )
        document["schema_version"] = "overview-1.0"
        document["schema_type"] = "overview"
        document.setdefault("title", novel.title)
        return document

    def _fallback_document(self, novel: Novel, chapters: list[Chapter]) -> dict:
        summary = novel.summary or ""
        arcs = novel.character_arcs or []
        return {
            "schema_version": "overview-1.0",
            "schema_type": "overview",
            "title": novel.title,
            "logline": summary[:100] if summary else "暂无",
            "hook": "",
            "genre": (novel.user_selected_genres or [None])[0],
            "estimated_episodes": max(len(chapters) // 2, 1),
            "market_comparable": "",
            "adaptation_difficulty": "待评估",
            "main_characters": [
                {
                    "name": arc.get("name", "未命名角色"),
                    "role": arc.get("role", ""),
                    "one_liner": self._arc_one_liner(arc),
                }
                for arc in arcs[:5]
            ],
            "plot_arc": {
                "setup": "",
                "inciting_incident": "",
                "rising_action": "",
                "climax": "",
                "resolution": "",
            },
            "episodes": [
                {
                    "episode_number": ch.chapter_num,
                    "title": ch.title,
                    "source_chapter": ch.title,
                    "one_line_summary": (ch.summary or "")[:100],
                    "key_scenes": [],
                }
                for ch in chapters[:10]
            ],
            "is_fallback": True,
        }

    @staticmethod
    def _arc_one_liner(arc: dict) -> str:
        if arc.get("one_liner"):
            return str(arc["one_liner"])
        inner = arc.get("arc")
        if isinstance(inner, dict):
            return str(inner.get("start", ""))[:50]
        if isinstance(inner, str):
            return inner[:50]
        return str(arc.get("arc_description", ""))[:50]


overview_service = OverviewService()
