import type { Episode, Novel, Screenplay } from './types'
import { buildAdaptationPlan } from './adaptation'

function scenes(episodeNum: number) {
  return [
    {
      id: `s${episodeNum}-1`,
      heading: episodeNum === 1 ? '内景 - 贾府 - 日' : '内景 - 潇湘馆 - 夜',
      action:
        episodeNum === 1
          ? '贾母高坐正中，王熙凤在旁侍立。黛玉缓步进堂，众人目光齐刷刷看来。'
          : '黛玉独坐窗边，手中帕子已被泪浸湿。窗外竹影摇曳。',
      dialogues: [
        {
          id: `d${episodeNum}-1`,
          character: episodeNum === 1 ? '贾母' : '黛玉',
          line: episodeNum === 1 ? '这就是外孙女儿？快近前来我看看。' : '这地方，终非久留之地。',
        },
        {
          id: `d${episodeNum}-2`,
          character: episodeNum === 1 ? '黛玉' : '宝玉',
          line: episodeNum === 1 ? '黛玉拜见外祖母。' : '妹妹怎么又哭了？',
          parenthetical: episodeNum === 2 ? '（轻声）' : undefined,
        },
      ],
    },
    {
      id: `s${episodeNum}-2`,
      heading: '内景 - 荣禧堂 - 日',
      action: '宝玉出场，与黛玉四目相对，二人皆是一怔。',
      dialogues: [
        {
          id: `d${episodeNum}-3`,
          character: '宝玉',
          line: episodeNum === 1 ? '这个妹妹我曾见过的。' : '今日天气正好，咱们去园子里走走？',
        },
      ],
    },
  ]
}

function strangerScenes(episodeNum: number) {
  return [
    {
      id: `st${episodeNum}-1`,
      heading: '内景 - 咖啡馆 - 日',
      action: '林晚坐在靠窗位置，面前摊着建筑图纸。沈云洲走到桌边。',
      dialogues: [
        {
          id: `std${episodeNum}-1`,
          character: '沈云洲',
          line: '这位置有人吗？',
        },
        {
          id: `std${episodeNum}-2`,
          character: '林晚',
          line: episodeNum === 1 ? '有。' : '……介意我坐一下吗？',
        },
      ],
    },
  ]
}

export const mockNovels: Novel[] = [
  {
    id: 'n_001',
    title: '红楼梦',
    author: '曹雪芹',
    status: 'ready_for_planning',
    userSelectedGenres: ['古装权谋'],
    wordCount: 730000,
    summary: '贾府兴衰与宝黛爱情悲剧。',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'n_002',
    title: '你好，陌生人',
    author: '佚名',
    status: 'preprocessing',
    userSelectedGenres: ['都市情感'],
    wordCount: 120000,
    createdAt: '2026-06-05T10:00:00Z',
  },
]

export const mockScreenplays: Screenplay[] = [
  {
    id: 'sp_001',
    novelId: 'n_001',
    title: '红楼梦 · 编剧版',
    schemaType: 'screenwriter',
    status: 'generating',
    adaptationPlan: buildAdaptationPlan(80, 36, '红楼梦'),
    isAutoGenerated: false,
  },
  {
    id: 'sp_002',
    novelId: 'n_001',
    title: '红楼梦 · 概览版',
    schemaType: 'overview',
    status: 'completed',
    isAutoGenerated: true,
  },
  {
    id: 'sp_003',
    novelId: 'n_002',
    title: '你好，陌生人 · 概览版',
    schemaType: 'overview',
    status: 'draft',
    isAutoGenerated: true,
  },
]

export const mockEpisodesByScreenplay: Record<string, Episode[]> = {
  sp_001: [
    {
      id: 'e1',
      screenplayId: 'sp_001',
      episodeNum: 1,
      title: '黛玉进府',
      sourceChapters: [1, 2],
      status: 'done',
      content: { scenes: scenes(1) },
    },
    {
      id: 'e2',
      screenplayId: 'sp_001',
      episodeNum: 2,
      title: '宝玉识黛玉',
      sourceChapters: [3],
      status: 'done',
      content: { scenes: scenes(2) },
    },
    {
      id: 'e3',
      screenplayId: 'sp_001',
      episodeNum: 3,
      title: '暗涌',
      sourceChapters: [4, 5],
      status: 'generating',
      content: { scenes: scenes(3) },
    },
    {
      id: 'e4',
      screenplayId: 'sp_001',
      episodeNum: 4,
      title: '待生成',
      sourceChapters: [6],
      status: 'pending',
      content: {
        scenes: [
          {
            id: 's4-1',
            heading: '待定场景',
            action: '（尚未生成，确认方案后可触发生成）',
            dialogues: [],
          },
        ],
      },
    },
  ],
  sp_003: [
    {
      id: 'e5',
      screenplayId: 'sp_003',
      episodeNum: 1,
      title: '初遇',
      sourceChapters: [1, 2],
      status: 'done',
      content: { scenes: strangerScenes(1) },
    },
    {
      id: 'e6',
      screenplayId: 'sp_003',
      episodeNum: 2,
      title: '试探',
      sourceChapters: [3],
      status: 'pending',
      content: { scenes: strangerScenes(2) },
    },
  ],
}

export function getScreenplayForNovel(novelId: string): Screenplay | undefined {
  return mockScreenplays.find(
    (s) => s.novelId === novelId && s.schemaType === 'screenwriter',
  ) ?? mockScreenplays.find((s) => s.novelId === novelId)
}

export function getOverviewScreenplay(novelId: string): Screenplay | undefined {
  return mockScreenplays.find(
    (s) => s.novelId === novelId && s.schemaType === 'overview',
  )
}
