/** 与 backend/app/models/enums.py + schemas 对齐 */

export type SchemaType = 'ai_video' | 'screenwriter' | 'overview'

export type NovelStatus =
  | 'uploaded'
  | 'preprocessing'
  | 'ready_for_planning'
  | 'preprocessing_failed'

export type ScreenplayStatus = 'draft' | 'planning' | 'generating' | 'completed'

export type EpisodeStatus = 'pending' | 'generating' | 'done' | 'failed'

export type TaskType = 'preprocess' | 'generate_episode' | 'generate_overview' | 'export'

export type TaskStatus = 'pending' | 'running' | 'done' | 'failed' | 'cancelled'

export type ConversationContext = 'preprocessing' | 'planning' | 'generation' | 'conversation'

export type ConversationStatus = 'active' | 'archived'

export type MessageRole = 'user' | 'assistant' | 'tool' | 'system'

export type ExportFormat = 'yaml' | 'pdf' | 'zip'

export type ExportStatus = 'pending' | 'running' | 'done' | 'failed'

export interface Timestamped {
  createdAt?: string
  updatedAt?: string
}

export interface Novel extends Timestamped {
  id: string
  title: string
  author?: string
  status: NovelStatus
  /** 对应后端 user_selected_genres；上传请求体字段仍为 genres */
  userSelectedGenres: string[]
  wordCount?: number
  summary?: string
}

export interface Screenplay extends Timestamped {
  id: string
  novelId: string
  title: string
  schemaType: SchemaType
  status: ScreenplayStatus
  adaptationPlan?: AdaptationPlan
  isAutoGenerated?: boolean
}

export interface SceneDialogue {
  id: string
  character: string
  line: string
  parenthetical?: string
}

export interface Scene {
  id: string
  heading: string
  action: string
  dialogues: SceneDialogue[]
}

export interface EpisodeContent {
  scenes: Scene[]
}

export interface Episode extends Timestamped {
  id: string
  screenplayId: string
  episodeNum: number
  title: string
  sourceChapters: number[]
  status: EpisodeStatus
  content: EpisodeContent
}

export interface Task extends Timestamped {
  id: string
  taskType: TaskType
  novelId?: string
  episodeId?: string
  celeryId?: string
  status: TaskStatus
  progress: number
  errorMessage?: string
  retryCount: number
}

export interface Conversation extends Timestamped {
  id: string
  title: string
  contextType: ConversationContext
  status: ConversationStatus
  novelId?: string
  screenplayId?: string
}

export interface Message {
  id: string
  conversationId: string
  role: MessageRole
  content?: string
  toolCalls?: ToolCall[]
  toolResults?: Record<string, unknown>[]
  tokenUsage?: Record<string, unknown>
  isPinned?: boolean
  isCompressed?: boolean
  createdAt?: string
}

/** 兼容 ChatPanel 使用的简化消息 */
export interface ChatMessage {
  id: string
  role: 'user' | 'assistant' | 'tool'
  content: string
  toolCalls?: ToolCall[]
}

export interface ToolCall {
  name: string
  args: string
  durationMs?: number
  status: 'success' | 'failed' | 'running'
}

export interface ExportJob extends Timestamped {
  id: string
  screenplayId: string
  exportFormat: ExportFormat
  status: ExportStatus
  fileUrl?: string
  expiresAt?: string
}

export interface AdaptationPlanItem {
  episodeNum: number
  title: string
  sourceChapters: number[]
  oneLineSummary?: string
}

export interface AdaptationPlan {
  totalChapters: number
  episodeCount: number
  items: AdaptationPlanItem[]
  reasoning?: string
}

export interface SchemaOption {
  type: SchemaType
  label: string
  tagline: string
  description: string
  audience: string
  highlights: string[]
}

// —— WebSocket 消息（Design 10.5.3）——

export type WsClientMessage =
  | { type: 'message'; content: string }
  | { type: 'stop' }

export type WsServerMessage =
  | { type: 'message_start'; conversation_id?: string }
  | { type: 'content_delta'; text: string }
  | { type: 'message_saved'; message_id: string }
  | { type: 'message_end' }
  | { type: 'tool_call'; name: string; args?: string; tool?: string }
  | { type: 'tool_result'; name: string; status: string; data?: unknown }
  | { type: 'episode_generated'; episode: Episode }
  | { type: 'task_progress'; progress: number; stage?: string; message?: string }
  | { type: 'error'; error: string }

export type NovelProgressWsMessage =
  | { type: 'progress'; id: number; event_type: string; payload: Record<string, unknown> }
  | { type: 'done' }

export type PreprocessProgressEvent =
  | { type: 'split_completed'; chapter_count: number }
  | { type: 'chapter_done'; chapter_num: number; progress: number }
  | { type: 'overview_done'; overview_id: string }
  | { type: 'preprocessing_done'; duration_seconds: number }
  | { type: 'preprocessing_failed'; error: string }
